[backup]
target = "/tmp/auto-test"
destination = "/tmp/auto-test/backup"
backup_name = ""
compression = "gzip"
link_mode = "ignore" # follow/preserve/ignore

[filter]
include = []
exclude = [
    ".venv",
    "dist/",
    "**.__pycache__/",
    "**/*.pyc",
    "**/*.key",
]

[retention]
keep_last = 4

[archive]
enabled = true
path = "/tmp/auto-test/archive"

[encryption]
enabled = false
# key_path = ""
