class BackuperError(Exception):
    ...

class ChecksumMismatchError(BackuperError):
    ...

class ChecksumNotFoundError(BackuperError):
    ...

class FilterEmptyError(BackuperError):
    ...

class NotEnoughDiskSpaceError(BackuperError):
    ...